# Generated by Django 4.2.28 on 2026-02-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('follows', models.IntegerField(default=0)),
                ('profile_visits', models.IntegerField(default=0)),
                ('caption_length', models.IntegerField(default=0)),
                ('hashtags', models.IntegerField(default=0)),
                ('reposts', models.IntegerField(default=0)),
                ('predicted_impressions', models.IntegerField(default=0)),
                ('viral_score', models.FloatField(default=0)),
                ('eng_rate', models.FloatField(default=0)),
                ('follow_rate', models.FloatField(default=0)),
                ('ai_viral_label', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
